### ISSUE TITLE
you realize we cant view the demo, right?

### ISSUE THREAD

**Issue by ghost** [josephg/noisejs#32]
this html file isnt just gonna magically create its own website, you know. i suggest maybe hosting it on your website or something. if someone wanted a demo, they would have to go through the trouble of downloading the whole repository. you realize that right?

**Comment by josephg** [comment]
Hi! Welcome to GitHub. I worked on this library for free, and provide it to the world for free. Sometimes, every few years I make it better. For free.

I don’t know if you intended it this way but your comment sounds smug and entitled. I don’t want to do you the favour of fixing the issue you’re describing because you insinuated I’m an idiot. Not only do I have no motivation to help you with this, my emotions want me to actively not fix this issue now out of petty spite.

Ask nicely or fork the repo & maintain your own version of my code. If you want free help from opensource maintainers, you won’t get it with comments like that.

**Comment by orionrush** [comment]
I just want to second, and further validate @josephg ’s assessment of the OP’s comment, so it’s not just one person’s opinion against another. The tone and attitude projected is caustic and isn’t going to be one that benefits this project, or realistically the OP as an individual, as a person. It’s a sad thing to see.

**Comment by mootari** [comment]
For anyone who actually knows to appreciate the work @josephg has put into this repo, be aware that you can open any file from GitHub repos with the correct content headers via https://raw.githack.com/ .

@minionthree I hope you were able to reflect on the feedback that you received here.

**Comment by ghost** [comment]
sorry for my tone

**Comment by ghost** [comment]
i found it i just had to mess around with his website directory

**Comment by josephg** [comment]
Glad you found a solution! If its an easy to fix broken link in the readme, I'd love a PR!

**Comment by bumbeishvili** [comment]
@josephg I think it can't be fixed with PR, but it's really easy for the repo owner to fix: 

Just 
* navigate to repo settings => 
*  in the sidebar choose pages => 
*  in the source choose a `master` and save.
 
 And it will work normally (no need to change anything in source code)

Also, please don't allow stupid comments to have influence over your work. You've done an amazing job which helped many people (myself included)

<img width="1036" alt="Screenshot 2021-07-19 at 11 12 12" src="https://user-images.githubusercontent.com/6873202/126118346-0e1e0fce-88e3-477c-af82-25e7cc5fa425.png">


<img width="347" alt="Screenshot 2021-07-19 at 11 13 00" src="https://user-images.githubusercontent.com/6873202/126118340-6da45fa0-fd25-4474-b1ea-337097c4c9d6.png">

<img width="812" alt="Screenshot 2021-07-19 at 11 13 48" src="https://user-images.githubusercontent.com/6873202/126118331-809ad63d-3154-4631-8909-3e0dcf1c947c.png">
